const fs = require('fs');
const { ethers } = require('ethers');

const LABEL = process.env.LABEL;
const RPCS = process.env.RPCS.split(',').map(x=>x.trim()).filter(Boolean);
const FACTORIES = process.env.FACTORIES.split(',').map(x=>{ const [address,from] = x.split(':'); return {address:ethers.utils.getAddress(address),fromBlock:Number(from)}; });
const OUT='encrypted-all-markets';
const MARKET_TOPIC='0x3f544a0e66146e1c515b04e3d00d07fabc299aa08db26f13ae0a2e3797503286';

const marketAbi=[
 'function name() view returns(string)',
 'function tokens() view returns(address ft,address xt,address gt,address collateral,address debtToken)',
 'function config() view returns(tuple(address treasurer,uint64 maturity,tuple(uint32 lendTakerFeeRatio,uint32 lendMakerFeeRatio,uint32 borrowTakerFeeRatio,uint32 borrowMakerFeeRatio,uint32 mintGtFeeRatio,uint32 mintGtFeeRef) feeConfig))'
];
const gtAbi=[
 'function getGtConfig() view returns(tuple(address collateral,address debtToken,address ft,address treasurer,uint64 maturity,tuple(address oracle,uint32 liquidationLtv,uint32 maxLtv,bool liquidatable) loanConfig))',
 'function totalSupply() view returns(uint256)'
];
const erc20Abi=['function symbol() view returns(string)','function decimals() view returns(uint8)','function totalSupply() view returns(uint256)','function balanceOf(address) view returns(uint256)'];
const oracleV2Abi=['function getPrice(address) view returns(uint256,uint8)','function oracles(address) view returns(address aggregator,address backupAggregator,int256 maxPrice,int256 minPrice,uint32 heartbeat,uint32 backupHeartbeat)'];
const oracleV1Abi=['function getPrice(address) view returns(uint256,uint8)','function oracles(address) view returns(address aggregator,address backupAggregator,uint32 heartbeat)'];
const feedAbi=[
 'function latestRoundData() view returns(uint80,int256,uint256,uint256,uint80)','function decimals() view returns(uint8)','function description() view returns(string)','function version() view returns(uint256)',
 'function pool() view returns(address)','function twapPeriod() view returns(uint32)','function baseToken() view returns(address)','function quoteToken() view returns(address)','function asset() view returns(address)',
 'function aTokenToBTokenPriceFeed() view returns(address)','function bTokenToCTokenPriceFeed() view returns(address)','function PRICE_FEED() view returns(address)','function MARKET() view returns(address)','function DURATION() view returns(uint32)',
 'function dusdOracle() view returns(address)','function xaueOracle() view returns(address)','function pharosOracle() view returns(address)','function result() view returns(uint256)','function pairIndex() view returns(uint256)'
];
function serialise(x){if(ethers.BigNumber.isBigNumber(x))return x.toString();if(Array.isArray(x))return x.map(serialise);if(x&&typeof x==='object'){const o={};for(const [k,v] of Object.entries(x))if(!/^\d+$/.test(k))o[k]=serialise(v);return o;}return x;}
async function safe(p){try{return {ok:true,value:serialise(await p)}}catch(e){return {ok:false,error:String(e)}}}
async function choose(){const attempts=[];for(const url of RPCS){try{const p=new ethers.providers.JsonRpcProvider(url);const [n,b]=await Promise.all([p.getNetwork(),p.getBlockNumber()]);attempts.push({url,ok:true,chainId:n.chainId,block:b});return {p,url,chainId:n.chainId,block:b,attempts};}catch(e){attempts.push({url,ok:false,error:String(e)})}}throw Error(JSON.stringify(attempts));}
async function logsAdaptive(p,address,from,to){let cur=from,span=250000;const logs=[],progress=[];while(cur<=to){const end=Math.min(to,cur+span-1);try{const part=await p.getLogs({address,fromBlock:cur,toBlock:end,topics:[MARKET_TOPIC]});logs.push(...part);progress.push({from:cur,to:end,count:part.length,span});cur=end+1;if(part.length<100&&span<1000000)span*=2;}catch(e){progress.push({from:cur,to:end,span,error:String(e)});if(span<=100)throw e;span=Math.max(100,Math.floor(span/2));}}return {logs,progress};}
async function feedInfo(p,a,block){if(!a||a===ethers.constants.AddressZero)return null;const c=new ethers.Contract(a,feedAbi,p);const code=await p.getCode(a,block);const getters={};for(const k of ['pool','twapPeriod','baseToken','quoteToken','asset','aTokenToBTokenPriceFeed','bTokenToCTokenPriceFeed','PRICE_FEED','MARKET','DURATION','dusdOracle','xaueOracle','pharosOracle','result','pairIndex'])getters[k]=await safe(c[k]({blockTag:block}));return {address:a,codeBytes:(code.length-2)/2,codeHash:ethers.utils.keccak256(code),latestRoundData:await safe(c.latestRoundData({blockTag:block})),decimals:await safe(c.decimals({blockTag:block})),description:await safe(c.description({blockTag:block})),version:await safe(c.version({blockTag:block})),getters};}
async function oracleInfo(p,a,asset,block){const v2=new ethers.Contract(a,oracleV2Abi,p);const c2=await safe(v2.oracles(asset,{blockTag:block}));if(c2.ok){const cfg=c2.value;return {version:'V2-shape',address:a,asset,config:c2,current:await safe(v2.getPrice(asset,{blockTag:block})),primary:await feedInfo(p,cfg.aggregator,block),backup:await feedInfo(p,cfg.backupAggregator,block)};}const v1=new ethers.Contract(a,oracleV1Abi,p);const c1=await safe(v1.oracles(asset,{blockTag:block}));return {version:c1.ok?'V1-shape':'unknown',address:a,asset,config:c1,current:await safe(v1.getPrice(asset,{blockTag:block})),primary:c1.ok?await feedInfo(p,c1.value.aggregator,block):null,backup:c1.ok?await feedInfo(p,c1.value.backupAggregator,block):null};}
(async()=>{fs.mkdirSync(OUT,{recursive:true});const {p,url,chainId,block,attempts}=await choose();const hdr=await p.getBlock(block);const map=new Map(),scans=[];for(const f of FACTORIES){const code=await p.getCode(f.address,block);const scan=await logsAdaptive(p,f.address,f.fromBlock,block);scans.push({factory:f.address,fromBlock:f.fromBlock,codeBytes:(code.length-2)/2,progress:scan.progress,logCount:scan.logs.length});for(const l of scan.logs){if(l.topics.length<4)continue;const market=ethers.utils.getAddress('0x'+l.topics[1].slice(-40));const collateral=ethers.utils.getAddress('0x'+l.topics[2].slice(-40));const debtToken=ethers.utils.getAddress('0x'+l.topics[3].slice(-40));map.set(market.toLowerCase(),{market,factory:f.address,createdBlock:l.blockNumber,createdTx:l.transactionHash,collateralEvent:collateral,debtEvent:debtToken});}}
const markets=[];for(const base of map.values()){try{const m=new ethers.Contract(base.market,marketAbi,p);const [name,tokens,config,code]=await Promise.all([m.name({blockTag:block}).catch(()=>''),m.tokens({blockTag:block}),m.config({blockTag:block}),p.getCode(base.market,block)]);const ft=new ethers.Contract(tokens.ft,erc20Abi,p),xt=new ethers.Contract(tokens.xt,erc20Abi,p),gt=new ethers.Contract(tokens.gt,gtAbi,p),coll=new ethers.Contract(tokens.collateral,erc20Abi,p),debt=new ethers.Contract(tokens.debtToken,erc20Abi,p);const [gtCfg,gtSupply,ftSupply,xtSupply,ftBal,xtBal,debtBal,collBal,debtSym,debtDec,collSym,collDec]=await Promise.all([gt.getGtConfig({blockTag:block}),gt.totalSupply({blockTag:block}),ft.totalSupply({blockTag:block}),xt.totalSupply({blockTag:block}),ft.balanceOf(base.market,{blockTag:block}),xt.balanceOf(base.market,{blockTag:block}),debt.balanceOf(base.market,{blockTag:block}),coll.balanceOf(tokens.gt,{blockTag:block}),debt.symbol({blockTag:block}).catch(()=>''),debt.decimals({blockTag:block}),coll.symbol({blockTag:block}).catch(()=>''),coll.decimals({blockTag:block})]);markets.push(serialise({...base,name,codeBytes:(code.length-2)/2,codeHash:ethers.utils.keccak256(code),config,tokens,debtMeta:{symbol:debtSym,decimals:debtDec},collateralMeta:{symbol:collSym,decimals:collDec},balances:{gtSupply,ftSupply,xtSupply,ftMarketBalance:ftBal,xtMarketBalance:xtBal,debtMarketBalance:debtBal,collateralGtBalance:collBal},gtConfig:gtCfg,debtOracle:await oracleInfo(p,gtCfg.loanConfig.oracle,tokens.debtToken,block),collateralOracle:await oracleInfo(p,gtCfg.loanConfig.oracle,tokens.collateral,block)}));}catch(e){markets.push({...base,fatalError:String(e)});}}
const output={label:LABEL,rpc:url,rpcAttempts:attempts,chainId,snapshot:{blockNumber:block,blockHash:hdr.hash,timestamp:hdr.timestamp},factories:scans,marketCount:markets.length,markets};fs.writeFileSync(`${OUT}/all-market-inventory.json`,JSON.stringify(output,null,2));console.log(JSON.stringify({label:LABEL,chainId,block,marketCount:markets.length,factories:scans.map(x=>({factory:x.factory,logCount:x.logCount}))},null,2));})().catch(e=>{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(`${OUT}/error.txt`,String(e.stack||e));process.exit(1)});
