'use strict';
const fs = require('fs');
const { ethers } = require('ethers');

const ROUTER = ethers.utils.getAddress('0x830fBad7Cd1c3Cc5B693Dc64b985f2901B253C5B');
const ADAPTER = ethers.utils.getAddress('0xBd795F755dbB5A5358D6c60AED53ceB486Fa8517');
const WHITELIST = ethers.utils.getAddress('0x03c4FCF963E5FBC0dC5851d2340624E70492acb9');
const RPCS = ['https://223.rpc.thirdweb.com','https://rpc.bsquared.network'];
const EXPLORERS = ['https://explorer.bsquared.network/api/v2','https://12d6a1773a-frontent-blockscout.bsquared.network/api/v2'];
const OUT='evidence';
const EIP1967_IMPL='0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc';
const EIP1967_ADMIN='0xb53127684a568b3173ae13b9f8a6016e019a8c3e8ee1178d6a717850b5d6103';
const wlAbi=['function isWhitelisted(address,uint8) view returns(bool)'];
const routerAbi=['function paused() view returns(bool)','function owner() view returns(address)','function version() view returns(string)'];
const erc20Abi=['function balanceOf(address) view returns(uint256)','function symbol() view returns(string)','function decimals() view returns(uint8)','function totalSupply() view returns(uint256)'];
async function safe(p){try{const v=await p;return {ok:true,value:ethers.BigNumber.isBigNumber(v)?v.toString():v}}catch(e){return {ok:false,error:String(e)}}}
async function getJson(url){const c=new AbortController();const timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{headers:{accept:'application/json','user-agent':'termmax-readonly-gate'},signal:c.signal});const t=await r.text();if(!r.ok)throw Error(`${r.status} ${t.slice(0,300)}`);return JSON.parse(t);}finally{clearTimeout(timer)}}
async function chooseRpc(){const attempts=[];for(const url of RPCS){try{const p=new ethers.providers.JsonRpcProvider(url,223);const [n,b]=await Promise.all([p.getNetwork(),p.getBlockNumber()]);attempts.push({url,ok:true,chainId:n.chainId,block:b});if(n.chainId===223)return {p,url,block:b,attempts};}catch(e){attempts.push({url,ok:false,error:String(e)})}}throw Error(JSON.stringify(attempts))}
async function tokenBalances(){const attempts=[];for(const base of EXPLORERS){for(const path of [`/addresses/${ROUTER}/token-balances`,`/addresses/${ROUTER}/tokens`]){const url=base+path;try{const j=await getJson(url);attempts.push({url,ok:true});return {url,attempts,items:Array.isArray(j)?j:(j.items||[])};}catch(e){attempts.push({url,ok:false,error:String(e)})}}}return {url:null,attempts,items:[],fatalError:'all explorer endpoints failed'}}
(async()=>{fs.mkdirSync(OUT,{recursive:true});const [rpc,exp]=await Promise.all([chooseRpc(),tokenBalances()]);const {p,url,block,attempts}=rpc;const hdr=await p.getBlock(block);const [routerCode,adapterCode,wlCode,impl,admin,native]=await Promise.all([p.getCode(ROUTER,block),p.getCode(ADAPTER,block),p.getCode(WHITELIST,block),p.getStorageAt(ROUTER,EIP1967_IMPL,block),p.getStorageAt(ROUTER,EIP1967_ADMIN,block),p.getBalance(ROUTER,block)]);const wl=new ethers.Contract(WHITELIST,wlAbi,p);const router=new ethers.Contract(ROUTER,routerAbi,p);const inventory=[];for(const item of exp.items){const token=item.token||{};const raw=token.address_hash||token.address||item.token_address;if(!raw||!ethers.utils.isAddress(raw))continue;const address=ethers.utils.getAddress(raw);const c=new ethers.Contract(address,erc20Abi,p);inventory.push({address,explorerValue:String(item.value??item.balance??''),explorerToken:token,balance:await safe(c.balanceOf(ROUTER,{blockTag:block})),symbol:await safe(c.symbol({blockTag:block})),decimals:await safe(c.decimals({blockTag:block})),totalSupply:await safe(c.totalSupply({blockTag:block}))});}
const result={rpc:{url,attempts,snapshot:{blockNumber:block,blockHash:hdr.hash,timestamp:hdr.timestamp}},explorer:exp,addresses:{router:ROUTER,adapter:ADAPTER,whitelist:WHITELIST},code:{routerHash:ethers.utils.keccak256(routerCode),routerBytes:(routerCode.length-2)/2,adapterHash:ethers.utils.keccak256(adapterCode),adapterBytes:(adapterCode.length-2)/2,whitelistHash:ethers.utils.keccak256(wlCode),whitelistBytes:(wlCode.length-2)/2,implementationSlot:impl,adminSlot:admin},state:{adapterWhitelisted:await safe(wl.isWhitelisted(ADAPTER,0,{blockTag:block})),paused:await safe(router.paused({blockTag:block})),owner:await safe(router.owner({blockTag:block})),version:await safe(router.version({blockTag:block})),nativeBalance:native.toString()},inventory};fs.writeFileSync(`${OUT}/B2_GATE.json`,JSON.stringify(result,null,2));fs.writeFileSync(`${OUT}/SUMMARY.json`,JSON.stringify({block,adapterWhitelisted:result.state.adapterWhitelisted,paused:result.state.paused,adapterCodeBytes:result.code.adapterBytes,tokenCount:inventory.length,positive:inventory.filter(x=>x.balance.ok&&x.balance.value!=='0').map(x=>({address:x.address,symbol:x.symbol,decimals:x.decimals,balance:x.balance,explorerToken:x.explorerToken}))},null,2));})().catch(e=>{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(`${OUT}/ERROR.txt`,String(e.stack||e));process.exitCode=1});
