'use strict';
const fs = require('fs');
const { ethers } = require('ethers');
const ROUTER = ethers.utils.getAddress('0x830fBad7Cd1c3Cc5B693Dc64b985f2901B253C5B');
const ADAPTER = ethers.utils.getAddress('0xBd795F755dbB5A5358D6c60AED53ceB486Fa8517');
const WHITELIST = ethers.utils.getAddress('0x03c4FCF963E5FBC0dC5851d2340624E70492acb9');
const EXPLORERS = ['https://explorer.bsquared.network/api/v2','https://12d6a1773a-frontent-blockscout.bsquared.network/api/v2'];
const RPCS = ['https://rpc.bsquared.network','https://223.rpc.thirdweb.com'];
const OUT='b2-blockscout-gate';
const EIP1967_IMPL='0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc';
const EIP1967_ADMIN='0xb53127684a568b3173ae13b9f8a6016e019a8c3e8ee1178d6a717850b5d6103';
const wlAbi=['function isWhitelisted(address,uint8) view returns(bool)'];
const routerAbi=['function paused() view returns(bool)','function owner() view returns(address)','function version() view returns(string)'];
const erc20Abi=['function balanceOf(address) view returns(uint256)','function symbol() view returns(string)','function decimals() view returns(uint8)','function totalSupply() view returns(uint256)'];
async function safe(p){try{const v=await p;return {ok:true,value:ethers.BigNumber.isBigNumber(v)?v.toString():v}}catch(e){return {ok:false,error:String(e)}}}
async function getJson(url){const r=await fetch(url,{headers:{accept:'application/json','user-agent':'termmax-readonly-security-research'}});const text=await r.text();if(!r.ok)throw new Error(`${r.status} ${text.slice(0,300)}`);return JSON.parse(text);}
async function explorerBalances(){const attempts=[];for(const base of EXPLORERS){for(const path of [`/addresses/${ROUTER}/token-balances`,`/addresses/${ROUTER}/tokens`]){try{const data=await getJson(base+path);attempts.push({url:base+path,ok:true});const items=Array.isArray(data)?data:(data.items||[]);return {url:base+path,attempts,items};}catch(e){attempts.push({url:base+path,ok:false,error:String(e)})}}}throw new Error(`all explorers failed ${JSON.stringify(attempts)}`)}
async function chooseRpc(){const attempts=[];for(const url of RPCS){try{const p=new ethers.providers.JsonRpcProvider(url,223);const [n,b]=await Promise.all([p.getNetwork(),p.getBlockNumber()]);attempts.push({url,ok:true,chainId:n.chainId,block:b});if(n.chainId===223)return {p,url,block:b,attempts};}catch(e){attempts.push({url,ok:false,error:String(e)})}}throw new Error(JSON.stringify(attempts))}
(async()=>{fs.mkdirSync(OUT,{recursive:true});const [exp,rpc]=await Promise.all([explorerBalances(),chooseRpc()]);const {p,url,block,attempts}=rpc;const hdr=await p.getBlock(block);const [routerCode,adapterCode,wlCode,impl,admin,native]=await Promise.all([p.getCode(ROUTER,block),p.getCode(ADAPTER,block),p.getCode(WHITELIST,block),p.getStorageAt(ROUTER,EIP1967_IMPL,block),p.getStorageAt(ROUTER,EIP1967_ADMIN,block),p.getBalance(ROUTER,block)]);const wl=new ethers.Contract(WHITELIST,wlAbi,p);const r=new ethers.Contract(ROUTER,routerAbi,p);const inventory=[];for(const item of exp.items){const tokenObj=item.token||{};const addr=tokenObj.address_hash||tokenObj.address||item.token_address; if(!addr||!ethers.utils.isAddress(addr))continue;const a=ethers.utils.getAddress(addr);const t=new ethers.Contract(a,erc20Abi,p);inventory.push({address:a,explorerValue:String(item.value??item.balance??''),explorerToken:tokenObj,balanceRpc:await safe(t.balanceOf(ROUTER,{blockTag:block})),symbolRpc:await safe(t.symbol({blockTag:block})),decimalsRpc:await safe(t.decimals({blockTag:block})),totalSupplyRpc:await safe(t.totalSupply({blockTag:block}))});}
const output={explorer:{url:exp.url,attempts:exp.attempts,itemCount:exp.items.length},rpc:{url,attempts,snapshot:{blockNumber:block,blockHash:hdr.hash,timestamp:hdr.timestamp}},addresses:{router:ROUTER,adapter:ADAPTER,whitelist:WHITELIST},code:{routerHash:ethers.utils.keccak256(routerCode),routerBytes:(routerCode.length-2)/2,adapterHash:ethers.utils.keccak256(adapterCode),adapterBytes:(adapterCode.length-2)/2,whitelistHash:ethers.utils.keccak256(wlCode),whitelistBytes:(wlCode.length-2)/2,implementationSlot:impl,adminSlot:admin},state:{adapterWhitelisted:await safe(wl.isWhitelisted(ADAPTER,0,{blockTag:block})),paused:await safe(r.paused({blockTag:block})),owner:await safe(r.owner({blockTag:block})),version:await safe(r.version({blockTag:block})),nativeBalance:native.toString()},inventory};fs.writeFileSync(`${OUT}/b2-uniswap-blockscout-gate.json`,JSON.stringify(output,null,2));console.log(JSON.stringify({block,explorer:exp.url,adapterWhitelisted:output.state.adapterWhitelisted,paused:output.state.paused,positive:inventory.filter(x=>x.balanceRpc.ok&&x.balanceRpc.value!=='0').map(x=>({address:x.address,symbol:x.symbolRpc,decimals:x.decimalsRpc,balance:x.balanceRpc,explorerToken:x.explorerToken}))},null,2));})().catch(e=>{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(`${OUT}/error.txt`,String(e.stack||e));console.error(e);process.exit(1)});
